# Generated by Django 2.2.5 on 2019-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mob_no',
            field=models.IntegerField(unique=True),
        ),
    ]
